<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-RJTB1K6" failures="1" tests="3" name="SCRUM-33 test(failed)" time="9.665" errors="0" timestamp="2025-04-15T17:44:14 GMT-05:00">
  <testcase classname="Test.TestSet01" name="try1" time="3.496">
    <skipped/>
  </testcase> <!-- try1 -->
  <testcase classname="Test.TestSet01" name="try1" time="2.841">
    <skipped/>
  </testcase> <!-- try1 -->
  <testcase classname="Test.TestSet01" name="try1" time="2.826">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.TestSet01.try1(TestSet01.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- try1 -->
  <testcase classname="Test.TestSet01" name="try5" time="0.0">
    <ignored/>
  </testcase> <!-- try5 -->
  <testcase classname="Test.TestSet01" name="try2" time="0.0">
    <ignored/>
  </testcase> <!-- try2 -->
  <testcase classname="Test.TestSet01" name="try3" time="0.0">
    <ignored/>
  </testcase> <!-- try3 -->
  <testcase classname="Test.TestSet01" name="try4" time="0.0">
    <ignored/>
  </testcase> <!-- try4 -->
</testsuite> <!-- SCRUM-33 test(failed) -->
